# Recommendation of Anime

*Dataset cleaning and preparation*

In [25]:
import pandas as pd

animes = pd.read_csv("/Users/mac/Desktop/personalisation/personalisation-23-24-main/mini/data/animes.csv")

animes = animes.drop(columns=[animes.columns[0]])

new_title_column = animes.columns[0]

animes.columns = ['title'] + list(animes.columns[1:])

animes = animes.drop_duplicates(subset=new_title_column, keep='first')

animes = animes.dropna()

animes

,title,synopsis,genre,aired,episodes,members,popularity,ranked,score,img_url,link
0,Haikyuu!! Second Season,Following their participation at the Inter-Hig...,"['Comedy', 'Sports', 'Drama', 'School', 'Shoun...","Oct 4, 2015 to Mar 27, 2016",25.0,489888,141,25.0,8.82,https://cdn.myanimelist.net/images/anime/9/766...,https://myanimelist.net/anime/28891/Haikyuu_Se...
1,Shigatsu wa Kimi no Uso,Music accompanies the path of the human metron...,"['Drama', 'Music', 'Romance', 'School', 'Shoun...","Oct 10, 2014 to Mar 20, 2015",22.0,995473,28,24.0,8.83,https://cdn.myanimelist.net/images/anime/3/671...,https://myanimelist.net/anime/23273/Shigatsu_w...
2,Made in Abyss,The Abyss—a gaping chasm stretching down into ...,"['Sci-Fi', 'Adventure', 'Mystery', 'Drama', 'F...","Jul 7, 2017 to Sep 29, 2017",13.0,581663,98,23.0,8.83,https://cdn.myanimelist.net/images/anime/6/867...,https://myanimelist.net/anime/34599/Made_in_Abyss
3,Fullmetal Alchemist: Brotherhood,"""In order for something to be obtained, someth...","['Action', 'Military', 'Adventure', 'Comedy', ...","Apr 5, 2009 to Jul 4, 2010",64.0,1615084,4,1.0,9.23,https://cdn.myanimelist.net/images/anime/1223/...,https://myanimelist.net/anime/5114/Fullmetal_A...
4,Kizumonogatari III: Reiketsu-hen,After helping revive the legendary vampire Kis...,"['Action', 'Mystery', 'Supernatural', 'Vampire']","Jan 6, 2017",1.0,214621,502,22.0,8.83,https://cdn.myanimelist.net/images/anime/3/815...,https://myanimelist.net/anime/31758/Kizumonoga...
...,...,...,...,...,...,...,...,...,...,...,...
19002,Naruto x UT,All-new animation offered throughout UNIQLO cl...,"['Action', 'Comedy', 'Super Power', 'Martial A...","Jan 1, 2011",1.0,34155,2382,1728.0,7.50,https://cdn.myanimelist.net/images/anime/3/304...,https://myanimelist.net/anime/10075/Naruto_x_UT
19003,Miira no Kaikata,High school student Sora Kashiwagi is accustom...,"['Slice of Life', 'Comedy', 'Supernatural']","Jan 12, 2018 to Mar 30, 2018",12.0,61459,1648,1727.0,7.50,https://cdn.myanimelist.net/images/anime/1486/...,https://myanimelist.net/anime/35828/Miira_no_K...
19004,Shinryaku!? Ika Musume,"After regaining her squid-like abilities, Ika ...","['Slice of Life', 'Comedy', 'Shounen']","Sep 27, 2011 to Dec 25, 2011",12.0,67422,1547,1548.0,7.56,https://cdn.myanimelist.net/images/anime/6/301...,https://myanimelist.net/anime/10378/Shinryaku_...
19005,Kingsglaive: Final Fantasy XV,"For years, the Niflheim Empire and the kingdom...",['Action'],"Jul 9, 2016",1.0,41077,2154,1544.0,7.56,https://cdn.myanimelist.net/images/anime/12/79...,https://myanimelist.net/anime/33082/Kingsglaiv...
19006,Chuunibyou demo Koi ga Shitai!: Kirameki no......,Although Yuuta Togashi and Rikka Takanashi hav...,"['Comedy', 'Drama', 'Romance', 'School', 'Slic...","Jun 19, 2013",1.0,128400,883,1533.0,7.56,https://cdn.myanimelist.net/images/anime/7/455...,https://myanimelist.net/anime/16934/Chuunibyou...

In [26]:
genre_column = 'genre'  

def get_unique_genres():
    if genre_column in animes.columns:

        animes[genre_column] = animes[genre_column].str.replace('[\[\]]', '', regex=True)
        
        all_genres = animes[genre_column].str.split(',').explode().str.strip()
        
        unique_genres = all_genres.drop_duplicates().dropna().values
        
        return unique_genres
    
    else:
        
        return f"The genre column '{genre_column}' does not exist in the dataset."

unique_genres = get_unique_genres()

print("all kinds of genres:")
print(unique_genres)

all kinds of genres:
["'Comedy'" "'Sports'" "'Drama'" "'School'" "'Shounen'" "'Music'"
 "'Romance'" "'Sci-Fi'" "'Adventure'" "'Mystery'" "'Fantasy'" "'Action'"
 "'Military'" "'Magic'" "'Supernatural'" "'Vampire'" "'Slice of Life'"
 "'Demons'" "'Historical'" "'Super Power'" "'Mecha'" "'Parody'"
 "'Samurai'" "'Seinen'" "'Police'" "'Psychological'" "'Josei'" "'Space'"
 "'Kids'" "'Shoujo Ai'" "'Ecchi'" "'Shoujo'" "'Horror'" "'Shounen Ai'"
 "'Cars'" "'Martial Arts'" "'Game'" "'Thriller'" "'Dementia'" "'Harem'" '']

In [27]:
title_column = 'title'

def get_genre_by_title(title):
    if title_column in animes.columns and genre_column in animes.columns:

        matching_row = animes[animes[title_column] == title]
        
        if not matching_row.empty:

            return matching_row[genre_column].values[0]
        else:

            return f"No anime found with title '{title}'"
        
    else:
        
        return f"Either the title column '{title_column}' or the genre column '{genre_column}' does not exist in the dataset."


title = "InuYasha Movie 2: Kagami no Naka no Mugenjo"  
genre = get_genre_by_title(title)

print("genre of anime " + title + ":")
print(genre)

genre of anime InuYasha Movie 2: Kagami no Naka no Mugenjo:
'Action', 'Adventure', 'Comedy', 'Historical', 'Demons', 'Supernatural', 'Drama', 'Magic', 'Romance', 'Fantasy', 'Shounen'

*Recommendation method 1*

Based on numerical value

In [28]:
features = ["title", "episodes", "popularity", "ranked", "score"]
subset_features = animes[features].dropna()
subset_features.describe()

           episodes    popularity        ranked         score
count  13675.000000  13675.000000  13675.000000  13675.000000
mean      12.523583   7999.478391   7108.839269      6.379982
std       49.247172   4844.068308   4167.194733      0.989704
min        1.000000      1.000000      1.000000      1.900000
25%        1.000000   3563.500000   3499.500000      5.710000
50%        1.000000   8091.000000   7070.000000      6.410000
75%       12.000000  12263.500000  10591.500000      7.110000
max     3057.000000  16320.000000  14675.000000      9.230000

In [29]:
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity

numeric_features = subset_features.select_dtypes(include=['int64', 'float64'])

scaled_features = StandardScaler().fit_transform(numeric_features)

similarities = cosine_similarity(scaled_features)

similarities_df = pd.DataFrame(similarities, index=subset_features['title'], columns=subset_features['title'])

similarities_df

title,Haikyuu!! Second Season,Shigatsu wa Kimi no Uso,Made in Abyss,Fullmetal Alchemist: Brotherhood,Kizumonogatari III: Reiketsu-hen,Mob Psycho 100 II,Sen to Chihiro no Kamikakushi,Kimetsu no Yaiba,Owarimonogatari 2nd Season,Code Geass: Hangyaku no Lelouch R2,...,Yowamushi Pedal: Re:RIDE,Pokemon Movie 02: Maboroshi no Pokemon Lugia Bakutan,Mekakucity V's,Amagami SS,Net-juu no Susume Special,Naruto x UT,Miira no Kaikata,Shinryaku!? Ika Musume,Kingsglaive: Final Fantasy XV,Chuunibyou demo Koi ga Shitai!: Kirameki no... Slapstick Noel
title,,,,,,,,,,,,,,,,,,,,,
Haikyuu!! Second Season,1.000000,0.999823,0.997449,0.977793,0.989524,0.997335,0.989918,0.999816,0.993517,0.999822,...,0.948165,0.935483,0.912128,0.945225,0.948562,0.955904,0.963555,0.966824,0.958392,0.947633
Shigatsu wa Kimi no Uso,0.999823,1.000000,0.998573,0.973962,0.991841,0.998422,0.992298,0.999543,0.995128,0.999677,...,0.950894,0.939379,0.913345,0.945315,0.952171,0.959258,0.965259,0.968476,0.961671,0.951227
Made in Abyss,0.997449,0.998573,1.000000,0.961243,0.997176,0.999891,0.997470,0.996984,0.998572,0.997431,...,0.959772,0.945666,0.921385,0.939928,0.958836,0.966372,0.966441,0.969702,0.968556,0.957365
Fullmetal Alchemist: Brotherhood,0.977793,0.973962,0.961243,1.000000,0.940126,0.962107,0.940962,0.979735,0.952731,0.978514,...,0.876403,0.859983,0.853171,0.911787,0.874220,0.882465,0.909448,0.913429,0.886235,0.874760
Kizumonogatari III: Reiketsu-hen,0.989524,0.991841,0.997176,0.940126,1.000000,0.997308,0.999795,0.988971,0.999085,0.989792,...,0.968619,0.945637,0.932498,0.923751,0.960385,0.969585,0.960684,0.964206,0.971479,0.957811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Naruto x UT,0.955904,0.959258,0.966372,0.882465,0.969585,0.963084,0.969131,0.950674,0.961795,0.951830,...,0.980656,0.990722,0.923054,0.962019,0.997770,1.000000,0.992546,0.993132,0.999961,0.995670
Miira no Kaikata,0.963555,0.965259,0.966441,0.909448,0.960684,0.962580,0.961477,0.958324,0.956069,0.959007,...,0.959692,0.991705,0.893813,0.987796,0.994564,0.992546,1.000000,0.999895,0.992936,0.994809
Shinryaku!? Ika Musume,0.966824,0.968476,0.969702,0.913429,0.964206,0.966040,0.964850,0.961808,0.959886,0.962462,...,0.962593,0.990585,0.898987,0.986388,0.994323,0.993132,0.999895,1.000000,0.993593,0.994320
Kingsglaive: Final Fantasy XV,0.958392,0.961671,0.968556,0.886235,0.971479,0.965357,0.971087,0.953311,0.963998,0.954446,...,0.980651,0.990538,0.923298,0.962780,0.997673,0.999961,0.992936,0.993593,1.000000,0.995648
Chuunibyou demo Koi ga Shitai!: Kirameki no... Slapstick Noel,0.947633,0.951227,0.957365,0.874760,0.957811,0.953278,0.959092,0.941904,0.949416,0.943278,...,0.958231,0.998938,0.883605,0.975194,0.999612,0.995670,0.994809,0.994320,0.995648,1.000000

In [30]:
top_30_df = similarities_df.iloc[:30, :30]

styled_df = top_30_df.style.background_gradient(cmap='Blues')

styled_df

In [31]:
animes.set_index('title', inplace=True)
animes.index.values

array(['Haikyuu!! Second Season', 'Shigatsu wa Kimi no Uso',
       'Made in Abyss', ..., 'Shinryaku!? Ika Musume',
       'Kingsglaive: Final Fantasy XV',
       'Chuunibyou demo Koi ga Shitai!: Kirameki no... Slapstick Noel'],
      dtype=object)

In [47]:
import numpy as np

anime = 'InuYasha Movie 2: Kagami no Naka no Mugenjo' 

sorted_indices = np.argsort(similarities[animes.index.get_loc(anime)])

top_n_similar_indices = sorted_indices[1:n+1]

top_n_similar = animes.index[top_n_similar_indices]

print(top_n_similar)

Index(['Lalala Lala-chan', 'Fuusen Inu Tinny 2nd Season',
       'Usagi no Mofy (TV 2016)', 'Mori no Senshi Bonolon',
       'Bemubemu Hunter Kotengu Tenmaru', 'Biriken Nandemo Shoukai',
       'Zhu Zhu Xia: Fan Wai - Pin Zhuang Tegong Dui', 'Great Hunt',
       'Kensaku to Enjin no ABC Days', 'Ganbare! Lulu Lolo'],
      dtype='object', name='title')

In [51]:
anime_title1 = 'Lalala Lala-chan'
row_data1 = animes.loc[anime_title1]

anime_title2 = 'Great Hunt'
row_data2 = animes.loc[anime_title2]

print(row_data1)
print(row_data2)

synopsis      Lala-chan is a slightly selfish squirrel girl....
genre                            'Adventure', 'Fantasy', 'Kids'
aired                              Mar 21, 2015 to Feb 26, 2016
episodes                                                   24.0
members                                                     120
popularity                                                14920
ranked                                                  12864.0
score                                                      4.93
img_url       https://cdn.myanimelist.net/images/anime/1785/...
link          https://myanimelist.net/anime/36549/Lalala_Lal...
Name: Lalala Lala-chan, dtype: object
synopsis      Great Hunt is a mysterious amalgamation of hea...
genre                                         'Comedy', 'Music'
aired                                      Apr 10, 2008 to 2008
episodes                                                   19.0
members                                                     156
popularity                                                14190
ranked                                                  12151.0
score                                                      5.08
img_url       https://cdn.myanimelist.net/images/anime/5/735...
link             https://myanimelist.net/anime/30602/Great_Hunt
Name: Great Hunt, dtype: object

*Recommendation method 2*

Based on type and content

In [30]:
animes = pd.read_csv("/Users/mac/Desktop/personalisation/personalisation-23-24-main/mini/data/animes.csv")

animes = animes.drop(columns=[animes.columns[0]])

new_title_column = animes.columns[0]
animes.columns = ['title'] + list(animes.columns[1:])

animes = animes.drop_duplicates(subset=new_title_column, keep='first')

animes = animes.dropna()

df_exploded = animes.assign(genres=animes['genre'].str.split(',')).explode('genre')
df_encoded = pd.get_dummies(df_exploded, columns=['genre'])
one_hot_animes = df_encoded.groupby('title').sum().reset_index()
one_hot_animes.index = one_hot_animes["title"].values

one_hot_animes

,title,synopsis,aired,episodes,members,popularity,ranked,score,img_url,link,...,"genre_['Supernatural', 'Music']","genre_['Supernatural', 'School']","genre_['Supernatural', 'Shounen']","genre_['Supernatural', 'Vampire']",genre_['Supernatural'],"genre_['Thriller', 'Mystery', 'Sci-Fi']","genre_['Thriller', 'Sci-Fi']",genre_['Thriller'],genre_['Vampire'],genre_[]
"""0""","""0""",This music video tells how a shy girl with a s...,"Oct 23, 2013",1.00,2594,7345,"11,123.00",4.77,https://cdn.myanimelist.net/images/anime/6/548...,https://myanimelist.net/anime/20707/0,...,0,0,0,0,0,0,0,0,0,0
"""Aesop"" no Ohanashi yori: Ushi to Kaeru, Yokubatta Inu","""Aesop"" no Ohanashi yori: Ushi to Kaeru, Yokub...",Based on Aesop's Fables.,"Mar 21, 1970",1.00,273,12413,"9,560.00",5.61,https://cdn.myanimelist.net/images/anime/3/651...,https://myanimelist.net/anime/25627/Aesop_no_O...,...,0,0,0,0,0,0,0,0,0,0
"""Bungaku Shoujo"" Kyou no Oyatsu: Hatsukoi","""Bungaku Shoujo"" Kyou no Oyatsu: Hatsukoi",Short episode bundled with the limited edition...,"Dec 26, 2009",1.00,16961,3466,"3,923.00",6.96,https://cdn.myanimelist.net/images/anime/2/799...,https://myanimelist.net/anime/7669/Bungaku_Sho...,...,0,0,0,0,0,0,0,0,0,0
"""Bungaku Shoujo"" Memoire","""Bungaku Shoujo"" Memoire",Episodes which depict the background stories o...,"Jun 25, 2010 to Dec 24, 2010",3.00,23504,2943,"2,087.00",7.40,https://cdn.myanimelist.net/images/anime/6/267...,https://myanimelist.net/anime/8481/Bungaku_Sho...,...,0,0,0,0,0,0,0,0,0,0
"""Bungaku Shoujo"" Movie","""Bungaku Shoujo"" Movie","The protagonist of the story, Konoha Inoue, is...","May 1, 2010",1.00,53766,1799,"1,778.00",7.48,https://cdn.myanimelist.net/images/anime/8/811...,https://myanimelist.net/anime/6408/Bungaku_Sho...,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
xxxHOLiC Rou,xxxHOLiC Rou,10 years after the events of xxxHOLiC Shunmuk...,"Apr 23, 2010 to Mar 9, 2011",2.00,50974,1869,312.00,8.21,https://cdn.myanimelist.net/images/anime/9/250...,https://myanimelist.net/anime/6864/xxxHOLiC_Rou,...,0,0,0,0,0,0,0,0,0,0
xxxHOLiC Shunmuki,xxxHOLiC Shunmuki,"For the appropriate price, your dearest wish c...","Feb 17, 2009 to Jun 23, 2009",2.00,53279,1813,420.00,8.13,https://cdn.myanimelist.net/images/anime/12/25...,https://myanimelist.net/anime/4918/xxxHOLiC_Sh...,...,0,0,0,0,0,0,0,0,0,0
Üks Uks,Üks Uks,Opening one's inner doors of conflict is the k...,2003,1.00,160,14107,"11,599.00",5.71,https://cdn.myanimelist.net/images/anime/11/71...,https://myanimelist.net/anime/29708/%C3%9Cks_Uks,...,0,0,0,0,0,0,0,0,0,0
ēlDLIVE,ēlDLIVE,Chuuta Kokonose is an orphan who lives with hi...,"Jan 8, 2017 to Mar 26, 2017",12.00,38062,2260,"7,377.00",6.23,https://cdn.myanimelist.net/images/anime/8/823...,https://myanimelist.net/anime/32878/%C4%93lDLIVE,...,0,0,0,0,0,0,0,0,0,0
◯,◯,Sawako Kabuki hand-drawn animation.,2010,1.00,1392,8820,"11,414.00",3.80,https://cdn.myanimelist.net/images/anime/3/763...,https://myanimelist.net/anime/31687/%E2%97%AF,...,0,0,0,0,0,0,0,0,0,0

In [31]:
genres_features = [col for col in one_hot_animes.columns if "genre" in col]
genres_features

['genres',
 "genre_['Action', 'Adventure', 'Cars', 'Comedy', 'Kids', 'Police']",
 "genre_['Action', 'Adventure', 'Cars', 'Comedy', 'Sci-Fi', 'Shounen']",
 "genre_['Action', 'Adventure', 'Cars', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Cars']",
 "genre_['Action', 'Adventure', 'Comedy', 'Demons', 'Drama', 'Ecchi', 'Horror', 'Mystery', 'Romance', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Comedy', 'Demons', 'Fantasy', 'Magic']",
 "genre_['Action', 'Adventure', 'Comedy', 'Demons', 'Fantasy', 'Martial Arts', 'Shounen', 'Super Power']",
 "genre_['Action', 'Adventure', 'Comedy', 'Demons', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Comedy', 'Demons', 'Shounen', 'Supernatural']",
 "genre_['Action', 'Adventure', 'Comedy', 'Demons', 'Supernatural', 'Martial Arts', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Demons', 'Supernatural', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Demons', 'Supernatural', 'Vampire']",
 "genre_['Action', 'Adventure', 'Comedy', 'Drama', 'Ecchi', 'Fantasy', 'Harem', 'Magic', 'Romance', 'School']",
 "genre_['Action', 'Adventure', 'Comedy', 'Drama', 'Ecchi', 'Mecha', 'Romance', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Comedy', 'Drama', 'Fantasy', 'Historical']",
 "genre_['Action', 'Adventure', 'Comedy', 'Drama', 'Fantasy', 'Josei']",
 "genre_['Action', 'Adventure', 'Comedy', 'Drama', 'Fantasy', 'Kids']",
 "genre_['Action', 'Adventure', 'Comedy', 'Drama', 'Fantasy', 'Magic', 'Military', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Drama', 'Fantasy', 'Shounen', 'Super Power']",
 "genre_['Action', 'Adventure', 'Comedy', 'Drama', 'Fantasy', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Drama', 'Harem', 'Martial Arts', 'Mecha', 'Romance', 'Sci-Fi', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Drama', 'Historical', 'Military', 'Romance']",
 "genre_['Action', 'Adventure', 'Comedy', 'Drama', 'Mecha', 'Sci-Fi', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Drama', 'Romance', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Comedy', 'Drama', 'Sci-Fi', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Drama', 'Sci-Fi', 'Space']",
 "genre_['Action', 'Adventure', 'Comedy', 'Drama', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Drama']",
 "genre_['Action', 'Adventure', 'Comedy', 'Ecchi', 'Fantasy', 'Seinen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Ecchi', 'Kids', 'Magic', 'Romance', 'Super Power', 'Supernatural']",
 "genre_['Action', 'Adventure', 'Comedy', 'Ecchi', 'Mecha', 'Military', 'Romance', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Comedy', 'Ecchi', 'Mecha', 'Sci-Fi', 'Space']",
 "genre_['Action', 'Adventure', 'Comedy', 'Ecchi', 'Parody', 'Seinen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Ecchi', 'Police', 'Sci-Fi', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Ecchi', 'Samurai', 'Seinen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Ecchi', 'Sci-Fi', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Ecchi', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Comedy', 'Fantasy', 'Game', 'Kids']",
 "genre_['Action', 'Adventure', 'Comedy', 'Fantasy', 'Game']",
 "genre_['Action', 'Adventure', 'Comedy', 'Fantasy', 'Historical', 'Samurai', 'Seinen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Fantasy', 'Josei']",
 "genre_['Action', 'Adventure', 'Comedy', 'Fantasy', 'Kids', 'Parody', 'Sci-Fi', 'Super Power']",
 "genre_['Action', 'Adventure', 'Comedy', 'Fantasy', 'Kids', 'Parody', 'Sports']",
 "genre_['Action', 'Adventure', 'Comedy', 'Fantasy', 'Kids']",
 "genre_['Action', 'Adventure', 'Comedy', 'Fantasy', 'Magic', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Fantasy', 'Magic']",
 "genre_['Action', 'Adventure', 'Comedy', 'Fantasy', 'Martial Arts', 'Shounen', 'Super Power']",
 "genre_['Action', 'Adventure', 'Comedy', 'Fantasy', 'Mecha', 'Sci-Fi', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Fantasy', 'Mecha']",
 "genre_['Action', 'Adventure', 'Comedy', 'Fantasy', 'Romance', 'Shoujo']",
 "genre_['Action', 'Adventure', 'Comedy', 'Fantasy', 'Romance']",
 "genre_['Action', 'Adventure', 'Comedy', 'Fantasy', 'Sci-Fi', 'Shounen', 'Super Power']",
 "genre_['Action', 'Adventure', 'Comedy', 'Fantasy', 'Sci-Fi', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Fantasy', 'Sci-Fi', 'Supernatural']",
 "genre_['Action', 'Adventure', 'Comedy', 'Fantasy', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Comedy', 'Fantasy', 'Shounen', 'Super Power']",
 "genre_['Action', 'Adventure', 'Comedy', 'Fantasy', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Comedy', 'Game', 'Mecha', 'Sci-Fi', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Game', 'Parody']",
 "genre_['Action', 'Adventure', 'Comedy', 'Harem', 'Mecha', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Comedy', 'Historical', 'Demons', 'Supernatural', 'Drama', 'Magic', 'Romance', 'Fantasy', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Historical', 'Demons', 'Supernatural', 'Magic', 'Romance', 'Fantasy', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Historical', 'Fantasy', 'Seinen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Historical', 'Martial Arts', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Historical', 'Martial Arts']",
 "genre_['Action', 'Adventure', 'Comedy', 'Historical', 'Mystery', 'Supernatural']",
 "genre_['Action', 'Adventure', 'Comedy', 'Historical', 'Romance', 'Samurai', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Historical', 'Romance', 'Samurai']",
 "genre_['Action', 'Adventure', 'Comedy', 'Historical', 'Samurai', 'Fantasy', 'Seinen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Historical', 'Samurai', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Kids', 'Drama', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Comedy', 'Kids', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Comedy', 'Kids', 'Mecha', 'Sci-Fi', 'Shounen', 'Super Power']",
 "genre_['Action', 'Adventure', 'Comedy', 'Kids', 'Sci-Fi', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Kids', 'Super Power']",
 "genre_['Action', 'Adventure', 'Comedy', 'Kids']",
 "genre_['Action', 'Adventure', 'Comedy', 'Magic', 'Fantasy', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Magic', 'Mecha', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Comedy', 'Magic', 'Romance', 'Sci-Fi', 'Shoujo']",
 "genre_['Action', 'Adventure', 'Comedy', 'Martial Arts', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Martial Arts']",
 "genre_['Action', 'Adventure', 'Comedy', 'Mecha', 'Military']",
 "genre_['Action', 'Adventure', 'Comedy', 'Mecha', 'Sci-Fi', 'Seinen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Mecha', 'Sci-Fi', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Mecha', 'Sci-Fi', 'Super Power']",
 "genre_['Action', 'Adventure', 'Comedy', 'Mecha', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Comedy', 'Mecha', 'Shounen', 'Space']",
 "genre_['Action', 'Adventure', 'Comedy', 'Mecha']",
 "genre_['Action', 'Adventure', 'Comedy', 'Mystery', 'Romance']",
 "genre_['Action', 'Adventure', 'Comedy', 'Mystery', 'Seinen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Mystery', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Parody', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Comedy', 'Police', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Comedy', 'Police']",
 "genre_['Action', 'Adventure', 'Comedy', 'Romance', 'Drama', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Comedy', 'Romance', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Comedy', 'Romance', 'School', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Romance', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'School', 'Supernatural']",
 "genre_['Action', 'Adventure', 'Comedy', 'Sci-Fi', 'Drama']",
 "genre_['Action', 'Adventure', 'Comedy', 'Sci-Fi', 'Shounen', 'Sports']",
 "genre_['Action', 'Adventure', 'Comedy', 'Sci-Fi', 'Super Power']",
 "genre_['Action', 'Adventure', 'Comedy', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Comedy', 'Seinen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Shounen', 'Super Power']",
 "genre_['Action', 'Adventure', 'Comedy', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Space']",
 "genre_['Action', 'Adventure', 'Comedy', 'Sports', 'Romance', 'Martial Arts']",
 "genre_['Action', 'Adventure', 'Comedy', 'Super Power', 'Demons', 'Magic']",
 "genre_['Action', 'Adventure', 'Comedy', 'Super Power', 'Demons', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Super Power', 'Drama', 'Fantasy', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Super Power', 'Fantasy', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Super Power', 'Kids']",
 "genre_['Action', 'Adventure', 'Comedy', 'Super Power', 'Martial Arts', 'Fantasy', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Super Power', 'Martial Arts', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Super Power', 'Supernatural', 'Drama', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Super Power', 'Supernatural', 'Magic', 'Vampire']",
 "genre_['Action', 'Adventure', 'Comedy', 'Super Power', 'Supernatural', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Supernatural', 'Drama', 'Josei']",
 "genre_['Action', 'Adventure', 'Comedy', 'Supernatural', 'Drama', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Supernatural', 'Martial Arts', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Supernatural', 'Romance']",
 "genre_['Action', 'Adventure', 'Comedy', 'Supernatural', 'Shounen']",
 "genre_['Action', 'Adventure', 'Comedy', 'Supernatural', 'Vampire']",
 "genre_['Action', 'Adventure', 'Comedy']",
 "genre_['Action', 'Adventure', 'Dementia', 'Historical', 'Military', 'Mystery', 'Shounen', 'Supernatural']",
 "genre_['Action', 'Adventure', 'Demons', 'Drama', 'Fantasy', 'Horror', 'Magic', 'Military', 'Romance', 'Supernatural']",
 "genre_['Action', 'Adventure', 'Demons', 'Drama', 'Fantasy', 'Horror', 'Magic', 'Supernatural']",
 "genre_['Action', 'Adventure', 'Demons', 'Drama', 'Fantasy', 'Horror', 'Military', 'Romance', 'Seinen', 'Supernatural']",
 "genre_['Action', 'Adventure', 'Demons', 'Drama', 'Fantasy', 'Horror', 'Military', 'Seinen', 'Supernatural']",
 "genre_['Action', 'Adventure', 'Demons', 'Drama', 'Fantasy', 'Magic']",
 "genre_['Action', 'Adventure', 'Demons', 'Drama', 'Horror', 'Super Power']",
 "genre_['Action', 'Adventure', 'Demons', 'Fantasy', 'Game', 'Kids', 'Magic', 'Sci-Fi', 'Supernatural']",
 "genre_['Action', 'Adventure', 'Demons', 'Fantasy', 'Historical', 'Martial Arts', 'Romance']",
 "genre_['Action', 'Adventure', 'Demons', 'Fantasy', 'Horror', 'Shoujo', 'Supernatural']",
 "genre_['Action', 'Adventure', 'Demons', 'Fantasy', 'Magic']",
 "genre_['Action', 'Adventure', 'Demons', 'Fantasy', 'Martial Arts', 'Romance']",
 "genre_['Action', 'Adventure', 'Demons', 'Fantasy', 'Sci-Fi', 'Shounen', 'Super Power']",
 "genre_['Action', 'Adventure', 'Demons', 'Fantasy', 'Shounen']",
 "genre_['Action', 'Adventure', 'Demons', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Demons', 'Game', 'Shounen']",
 "genre_['Action', 'Adventure', 'Demons', 'Kids', 'Magic', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Demons', 'Magic', 'Martial Arts', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Demons', 'Romance', 'Martial Arts', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Demons', 'Supernatural', 'Magic', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Demons', 'Supernatural', 'Romance', 'Martial Arts', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Drama', 'Fantasy', 'Historical', 'Magic', 'Shounen']",
 "genre_['Action', 'Adventure', 'Drama', 'Fantasy', 'Historical', 'Romance']",
 "genre_['Action', 'Adventure', 'Drama', 'Fantasy', 'Historical', 'Shounen']",
 "genre_['Action', 'Adventure', 'Drama', 'Fantasy', 'Historical', 'Supernatural']",
 "genre_['Action', 'Adventure', 'Drama', 'Fantasy', 'Historical']",
 "genre_['Action', 'Adventure', 'Drama', 'Fantasy', 'Mystery', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Drama', 'Fantasy', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Drama', 'Fantasy', 'Shoujo']",
 "genre_['Action', 'Adventure', 'Drama', 'Fantasy', 'Shounen']",
 "genre_['Action', 'Adventure', 'Drama', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Drama', 'Historical', 'Mystery', 'Romance', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Drama', 'Historical', 'Romance']",
 "genre_['Action', 'Adventure', 'Drama', 'Historical', 'Samurai']",
 "genre_['Action', 'Adventure', 'Drama', 'Historical', 'Sci-Fi', 'Seinen']",
 "genre_['Action', 'Adventure', 'Drama', 'Historical', 'Seinen']",
 "genre_['Action', 'Adventure', 'Drama', 'Historical']",
 "genre_['Action', 'Adventure', 'Drama', 'Horror', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Drama', 'Kids', 'Mecha', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Drama', 'Magic', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Drama', 'Magic', 'Romance', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Drama', 'Martial Arts', 'Romance', 'Shounen']",
 "genre_['Action', 'Adventure', 'Drama', 'Martial Arts', 'Romance']",
 "genre_['Action', 'Adventure', 'Drama', 'Martial Arts', 'Shounen']",
 "genre_['Action', 'Adventure', 'Drama', 'Martial Arts']",
 "genre_['Action', 'Adventure', 'Drama', 'Mecha', 'Military', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Drama', 'Mecha', 'Sci-Fi', 'Shounen', 'Space']",
 "genre_['Action', 'Adventure', 'Drama', 'Mecha', 'Sci-Fi', 'Shounen']",
 "genre_['Action', 'Adventure', 'Drama', 'Mecha', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Drama', 'Military', 'Sci-Fi', 'Space']",
 "genre_['Action', 'Adventure', 'Drama', 'Mystery', 'Romance', 'Sci-Fi', 'Shoujo', 'Space']",
 "genre_['Action', 'Adventure', 'Drama', 'Mystery', 'Shounen']",
 "genre_['Action', 'Adventure', 'Drama', 'Psychological', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Drama', 'Romance', 'Fantasy', 'Shounen']",
 "genre_['Action', 'Adventure', 'Drama', 'Sci-Fi', 'Shounen']",
 "genre_['Action', 'Adventure', 'Drama', 'Sci-Fi', 'Space']",
 "genre_['Action', 'Adventure', 'Drama', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Drama', 'Seinen']",
 "genre_['Action', 'Adventure', 'Drama', 'Shoujo']",
 "genre_['Action', 'Adventure', 'Drama', 'Shounen']",
 "genre_['Action', 'Adventure', 'Drama', 'Thriller', 'Seinen']",
 "genre_['Action', 'Adventure', 'Ecchi', 'Fantasy', 'Magic', 'Shounen', 'Supernatural']",
 "genre_['Action', 'Adventure', 'Ecchi', 'Fantasy', 'Parody', 'Shounen']",
 "genre_['Action', 'Adventure', 'Ecchi', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Ecchi', 'Shounen']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Comedy', 'Mecha', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Comedy', 'Shounen']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Comedy', 'Super Power', 'Shounen']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Comedy']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Drama', 'Shounen']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Game', 'Kids']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Game', 'Magic', 'Mystery', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Game', 'Magic', 'Supernatural']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Game', 'Magic']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Game', 'Romance']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Game', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Game', 'Shounen']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Game']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Harem']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Historical', 'Magic']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Historical', 'Martial Arts', 'Romance']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Historical', 'Martial Arts']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Historical', 'Military', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Historical', 'Sci-Fi', 'Supernatural']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Historical']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Horror', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Kids', 'Magic', 'Supernatural']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Kids', 'Sci-Fi', 'Super Power']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Kids', 'Supernatural']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Kids']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Magic', 'Drama', 'Seinen']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Magic', 'Mecha', 'Sci-Fi', 'Shounen', 'Space']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Magic', 'Mecha', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Magic', 'Mecha']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Magic', 'Military']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Magic', 'Mystery', 'School', 'Supernatural']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Magic', 'Mystery']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Magic', 'Romance', 'Shounen', 'Supernatural']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Magic', 'Romance', 'Supernatural', 'Shounen']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Magic', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Magic', 'Shounen', 'Supernatural']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Magic', 'Shounen']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Magic', 'Space', 'Mecha', 'Sci-Fi', 'Shounen']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Magic', 'Supernatural']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Magic']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Martial Arts', 'Shounen', 'Super Power']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Martial Arts']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Mecha', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Mecha']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Military']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Romance', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Romance', 'Supernatural', 'Drama', 'Mystery', 'Shounen']",
 "genre_['Action', 'Adventure', 'Fantasy', 'School', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Sci-Fi', 'Shounen']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Sci-Fi', 'Slice of Life']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Shounen', 'Super Power']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Shounen']",
 "genre_['Action', 'Adventure', 'Fantasy', 'Supernatural']",
 "genre_['Action', 'Adventure', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Game', 'Demons', 'Shounen']",
 "genre_['Action', 'Adventure', 'Game', 'Harem', 'Mecha', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Game', 'Kids', 'Sci-Fi']",
 "genre_['Action', 'Adventure', 'Game', 'Kids']",
 "genre_['Action', 'Adventure', 'Game', 'Mecha', 'School', 'Sci-Fi', 'Shounen']",
 "genre_['Action', 'Adventure', 'Game', 'Mecha', 'Sci-Fi', 'Shounen']",
 "genre_['Action', 'Adventure', 'Harem', 'Comedy', 'Magic', 'Romance', 'Ecchi', 'Fantasy', 'School']",
 "genre_['Action', 'Adventure', 'Harem', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Harem', 'Historical', 'Martial Arts', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Harem', 'Magic', 'Romance', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Historical', 'Demons', 'Martial Arts', 'Samurai', 'Shounen']",
 "genre_['Action', 'Adventure', 'Historical', 'Demons', 'Romance', 'Martial Arts', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Historical', 'Demons', 'Supernatural', 'Samurai', 'Shounen']",
 "genre_['Action', 'Adventure', 'Historical', 'Drama']",
 "genre_['Action', 'Adventure', 'Historical', 'Ecchi', 'Martial Arts', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Historical', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Historical', 'Martial Arts', 'Romance']",
 "genre_['Action', 'Adventure', 'Historical', 'Martial Arts', 'Samurai']",
 "genre_['Action', 'Adventure', 'Historical', 'Martial Arts', 'Shounen']",
 "genre_['Action', 'Adventure', 'Historical', 'Romance', 'Martial Arts', 'Fantasy']",
 "genre_['Action', 'Adventure', 'Historical', 'Samurai', 'Seinen']",

In [32]:
anime = 'InuYasha Movie 2: Kagami no Naka no Mugenjo'
one_hot_animes.loc[anime]

title                                            InuYasha Movie 2: Kagami no Naka no Mugenjo
synopsis                                   Inuyasha and company have finally destroyed Na...
aired                                                                           Dec 21, 2002
episodes                                                                                1.00
members                                                                                71989
                                                                 ...
genre_['Thriller', 'Mystery', 'Sci-Fi']                                                    0
genre_['Thriller', 'Sci-Fi']                                                               0
genre_['Thriller']                                                                         0
genre_['Vampire']                                                                          0
genre_[]                                                                                   0
Name: InuYasha Movie 2: Kagami no Naka no Mugenjo, Length: 4506, dtype: object

In [33]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity

if 'genre' in animes.columns:
    animes['genre'] = animes['genre'].astype(str)
    
    df_exploded = animes.assign(genres=animes['genre'].str.split(',')).explode('genre')
    
    df_encoded = pd.get_dummies(df_exploded, columns=['genre'])
    
    one_hot_animes = df_encoded.groupby('title').sum().reset_index()
    
    one_hot_animes.index = one_hot_animes["title"].values

    genres_features = [col for col in one_hot_animes.columns if 'genre_' in col]

    subset_features = one_hot_animes[genres_features]

    subset_features = subset_features.fillna(0)

    scaled_features = StandardScaler().fit_transform(subset_features)

    similarities = cosine_similarity(scaled_features)

    similarities = pd.DataFrame(similarities, columns=subset_features.index, index=subset_features.index)

    similarities.iloc[:50, :50].style.background_gradient(cmap='Purples')

    anime = 'InuYasha Movie 2: Kagami no Naka no Mugenjo'
    n = 10

    top_n_similar = similarities.sort_values(by=anime, ascending=False)[anime].index[1:n+1]

    print(top_n_similar)

Index(['InuYasha Movie 3: Tenka Hadou no Ken',
       'InuYasha Movie 2: Kagami no Naka no Mugenjo',
       'InuYasha Movie 1: Toki wo Koeru Omoi', 'Death Note',
       'Yakushiji Ryouko no Kaiki Jikenbo', 'Death Note: Rewrite',
       'Mahou Shoujo Madoka★Magica Movie 3: Hangyaku no Monogatari',
       'Omoide no Marnie',
       'Danganronpa: Kibou no Gakuen to Zetsubou no Koukousei The Animation',
       'Mouryou no Hako'],
      dtype='object')

In [53]:
print(similarities)

[[1.         0.99982309 0.99744904 ... 0.96682434 0.95839157 0.94763307]
 [0.99982309 1.         0.99857282 ... 0.96847585 0.96167061 0.95122665]
 [0.99744904 0.99857282 1.         ... 0.96970232 0.96855611 0.9573649 ]
 ...
 [0.96682434 0.96847585 0.96970232 ... 1.         0.99359258 0.99431951]
 [0.95839157 0.96167061 0.96855611 ... 0.99359258 1.         0.9956479 ]
 [0.94763307 0.95122665 0.9573649  ... 0.99431951 0.9956479  1.        ]]